### ISSUE TITLE
Include star rating in get_matches()

### ISSUE THREAD

**Issue by DMAgit** [dchoruzy/hltv-data#1]
### Feature request

Hey, is there a way to get the star rating of upcoming matches within the package? I think it would be appropriate to return it within the get_mathces method.

**Comment by Vcoss** [comment]
I was wanting the same thing.  What I did was get top 30 then compare the teams myself.  It would be nice to have it built in however.

**Comment by dchoruzy** [comment]
@DMAgit  @Vcoss 
took me a while but I added it!
