### ISSUE TITLE
error of use hltv_client.get_matches()

### ISSUE THREAD

**Issue by KMHBUG** [dchoruzy/hltv-data#4]
'NoneType' object has no attribute 'find_all'

code:
from hltv_data import HLTVClient
hltv_client = HLTVClient()
matches = hltv_client.get_matches()
for match in matches:
    event = match["event"]
    date = match["date"]
    team_1 = match["team_1"]
    team_2 = match["team_2"]
    star_rating = match["star_rating"]
    print(f"{event} - {date} - {team_1} vs {team_2} - {star_rating}")

**Comment by michihupf** [comment]
The implementation of the webscraper broke, HLTV executes javascript to basically load the entire page. I am pretty sure `requests` can't handle that.

**Comment by R0chaa** [comment]
sup man, I'm right now trying to implement some funcs using GetResults but i'm stuck in the 'find_all' problem

how cain i fix that? whitout results I dont know what to do ;)

**Comment by dchoruzy** [comment]
@michihupf   @R0chaa 
I have updated repository. 
Please take a look if it works for you and in case of any problems please create new Issue
